### ISSUE TITLE
Add a Page to Showcase the Explorations Team's Projects

### ISSUE THREAD

**Issue by DannyS03** [availproject/availproject.github.io#104]
This page can serve as a guide, providing a table format that succinctly outlines each project, accompanied by brief explanations to give users a quick overview. It can also direct users to various pages on the documentation for more in-depth information. Alternatively, we have the option to integrate the Explorations Team repo as a submodule, allowing us to host the README directly on the site.

**Comment by swarna1101** [comment]
#119
