### ISSUE TITLE
Add Hosting Info Column to Node Types Comparison Table

### ISSUE THREAD

**Issue by DannyS03** [availproject/availproject.github.io#106]
## Context

The [Node Types Comparison Table](https://availproject.github.io/operate/node-types/#node-types-comparison) currently provides a comparison of different node types but lacks information on who typically hosts each type of node. This additional information can offer clarity to readers, especially those unfamiliar with the different node types, and guide them on which node may be relevant to their role or use case.

## Acceptance Criteria

- [x] A new column titled “Typically Hosted By” is added to the Node Types Comparison Table.
- [x] The new column is populated with concise information specifying who typically hosts each type of node, e.g., 
  - **RPC Node:** Hosted by xyz.
  - **Relay Node:** Suitable for those setting up their own LC network needing to connect through firewalls.

**Comment by swarna1101** [comment]
#118

**Comment by DannyS03** [comment]
Mainly addressed in https://github.com/availproject/availproject.github.io/pull/118.
