### ISSUE TITLE
Initial CI Workflow for Docs

### ISSUE THREAD

**Issue by salmad3** [availproject/availproject.github.io#120]
## Context

Collaborate with the DevOps team to establish and execute a comprehensive end-to-end CI workflow for the Avail docs.

## Acceptance Criteria

Outlined below are the proposed initial priorities for the documentation Continuous Integration (CI) process:

- [x] **Site Deployment:** "`yarn install` and `yarn build`"
  
- [x] **Automated Lint Checks**: #73
  - Implement automated lint checks, which should encompass:
    - **Link Validation:** We possess an existing script for this, but it's open for modifications to enhance its efficiency.
    - **Version Checks:** Ensure that the documentation aligns with the current version of the product or software.

**Comment by DannyS03** [comment]
**2023-10-10 Update:**

- Syncing with DevOps this week to commence.

**Comment by salmad3** [comment]
We've add this with lint checks. Will open new issues for next phase of CI.
