### ISSUE TITLE
Avail Light Client Lift-off

### ISSUE THREAD

**Issue by 0xkelsey** [availproject/availproject.github.io#290]
This isn't necessarily an issue but a solution to those finding it difficult to run an avail node which would enable participation in the Avail light client lift-off and subsequently lead to the minting of the participation nft.

Visit mintair.xyz, connect your metamask wallet and make a $14.99 (an automactic 3 months subscription) payment. Nagivate to active node after payment and copy your public key. 

Proceed to the avail light client lift-off link powered by Blobscriptions and do the challenges so as to mint the nft.

**Comment by Gconcept1** [comment]
“Thanks your contribution was really helpful”

**Comment by OsujiJr** [comment]
I really appreciate this; it was really helpful.
