### ISSUE TITLE
Update docs with latest client release version

### ISSUE THREAD

**Issue by vthunder** [availproject/availproject.github.io#42]
Looks like we released a new version but didn't update the docs. We need to:
- [x] update the docs with the latest release
- [ ] make sure we integrate updating our docs into the release process so this doesn't happen again (can be filed as a separate issue if necessary)

See here for impact of this issue in the wild: https://twitter.com/ri5hitripathi/status/1694758481553936629

**Comment by swarna1101** [comment]
#45 fix the first task
