### ISSUE TITLE
Move docs to `docs.availproject.org` domain

### ISSUE THREAD

**Issue by vthunder** [availproject/availproject.github.io#48]
Docs are currently on a separate site implemented using docusaurus and hosted on github. Staging site hosted on digitalocean.

- [Repository](https://github.com/availproject/availproject.github.io)
- [Live site at availproject.github.io](https://availproject.github.io/)
- [Staging (go/docs-staging)](https://docs-refresh-2-rjp2q.ondigitalocean.app/)

We want to host the docs at docs.availproject.org instead of github so it's all under the same domain (but still a separate site from the main site).

Once it's hosted at the new location, please make sure to submit the site to Google for crawling/indexing.

**Comment by vthunder** [comment]
I'm told that we can keep the current hosting on GitHub and add a CNAME file with the domain to use. Let's do that now instead of waiting for a larger redesign. @jakubcech can you take care of the DNS record?

**Comment by vthunder** [comment]
See instructions here https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by vthunder** [comment]
@abheektripathy fyi let's move fast on this please

**Comment by abheektripathy** [comment]
@vthunder as per our previous conversation, i don't settings permissions to this repo, should i unassign myself here?

**Comment by vthunder** [comment]
Yep this is done
