### ISSUE TITLE
Documentation reorganization part 2

### ISSUE THREAD

**Issue by vthunder** [availproject/availproject.github.io#50]
After the last round of reorganization, a few things about the outline could use some refinement:

* “Getting Started with Avail” could be shortened to just “Getting Started”? it’s all about Avail
* “For Validators”
  * Not sure where networks should live, but not in here imo
  * Instructions for setting up validators should be at this level, without having to go one level deeper into “Run avail”
  * light client instructions should probably not live in here, rather it should go under the development guide. There could (should) be a link from somewhere in the validator docs over to the light client setup, for validators that want to run one.
* “Development guide”
  * light client setup article should probably be the first thing here
  * “Developing on Avail” doesn’t work for me. If it’s an overview, let’s call it something like “API & SDK Overview”? Or if it’s meant to be something else, let’s discuss.

**Comment by DannyS03** [comment]
Thanks, @vthunder. Let's slightly deviate from the original plan to keep things straightforward. I propose adding a "Node Guide" section with some other tweaks. Here is a proposal for the next iteration:

<img src="https://github.com/availproject/availproject.github.io/assets/25497083/8eaf759c-96c2-459b-82c8-1a47ded23e61" width="200" />

> The goal is to still progressively build out each section, with the flexibility to adjust the scope as we proceed - so treating this as a "provisional structure."

**Comment by swarna1101** [comment]
imo this looks good @DannyS03 🙌

**Comment by vthunder** [comment]
I think those "About Avail" topics shouldn't be at the top, they are not that important to learn up front before diving into the rest imo. Chill & slashing for example is something that only validators should have to learn, and they can learn it after they do the initial setup.

Re: the Node Guide, hmmm. I don't know that everyone will know to look under "Node Guide" for client info. Maybe if we call it "Node & Client Guide"?

Still not sure that the "Avail Networks" should live in there with the node/client info.

@prabal-banerjee any opinion on the proposed documentation outline?

**Comment by swarna1101** [comment]
Can we then follow this one as planned?
Link - https://docs.google.com/document/d/1EHCJb_CX25rrPjYo6mL10zc-zkpldRQe/edit?usp=sharing&ouid=115067671769264520107&rtpof=true&sd=true

cc: @prabal-banerjee
