### ISSUE TITLE
Figure out sire structure for new redesign (in Figma)

### ISSUE THREAD

**Issue by vthunder** [availproject/availproject.github.io#68]
Redesign in Figma has a navbar that has a single item for documentation and other items for other things (like tools etc). Current design has 
One of the good things on the previous doc site was the left pane contained the entire docs links. Now they are trimmed to the particular section. This might be personal opinion, but if someone goes to the wrong section, their flow to the correct section is not easy in the current setup.

**Comment by salmad3** [comment]
I believe this issue is now out of scope based on the new efforts to migrate to a new documentation platform and the recent updates to the sidebar. Please reopen if otherwise.
