### ISSUE TITLE
Enhance UI after Docs Refresh

### ISSUE THREAD

**Issue by salmad3** [availproject/availproject.github.io#70]
## Context

The docs site requires styling improvements after the initial refresh.

## Acceptance Criteria

- [x] Improve Font Styling
   - Make text easier to read (font styling)
   - Generally enhance font colors & weights
- [x] Improve tab styling: https://github.com/availproject/availproject.github.io/issues/111
- [x] Improve codeblocks: https://github.com/availproject/availproject.github.io/issues/110

**Comment by vthunder** [comment]
@abheektripathy let's discuss getting this onto your backlog

**Comment by salmad3** [comment]
Completed recently - https://docs.availproject.org/

Will open a new issue for more targeted styling requests, keeping in mind the intent to migrate to a new platform with a new design.
