### ISSUE TITLE
Update References to Substrate Following Its Integration into Polkadot SDK

### ISSUE THREAD

**Issue by DannyS03** [availproject/availproject.github.io#71]
## Context

Substrate has recently been integrated into the [Polkadot SDK monorepo](https://github.com/paritytech/polkadot-sdk). Given that Avail is a Substrate-based chain, it's important to check and update all references to Substrate and Polkadot accordingly.

## Acceptance Criteria

*The following should be done for the documentation and all READMEs*

- [x] Confirm that we can continue to use the term "Substrate" since Avail doesn't rely on features beyond what was available in the original Substrate source.
- [x] Update references to include a note like "Substrate (now part of Polkadot SDK)" where appropriate, to indicate both the historical and current context.
- [x] Ensure that any links pointing to the now-archived Substrate repository are updated to point to the new Polkadot-SDK repository.

## Additional Context

Note that the Polkadot-SDK README mentions plans to relocate Polkadot-specific runtime source, implying that the SDK could be seen as the next iteration or successor to Substrate.
> This directory currently contains runtimes for the Polkadot, Kusama, Westend, and Rococo networks. In the future, these will be relocated to the [runtimes](https://github.com/polkadot-fellows/runtimes/) repository.

**Comment by swarna1101** [comment]
#75

**Comment by vthunder** [comment]
#75 is merged so this can be marked done, correct?

**Comment by swarna1101** [comment]
@DannyS03 I believe this issue we can close as it is implemented
